### ISSUE TITLE
Feature request: clear from cursor to end of term

### ISSUE THREAD

**Issue by giann** [hoelzro/lua-term#21]
It would be nice to be able to clear from the cursor to the end of the terminal

**Comment by hoelzro** [comment]
@giann I just added [this commit](https://github.com/hoelzro/lua-term/commit/375fa065efc9a95b289371cf0eb7bf8b3be0bc9c) - if that does what you need, I can cut a new release!

**Comment by giann** [comment]
Perfect

**Comment by Tieske** [comment]
since it has ben added, I think this can be closed
