### ISSUE TITLE
Please release again

### ISSUE THREAD

**Issue by alerque** [hoelzro/lua-term#25]
We're getting beg reports on *downstream* packaging in Arch Linux asking us to patch this library with #19.

Instead of going down that road I'd like to just request a new release that includes the known fixes and we can package that.

Thanks.

**Comment by alerque** [comment]
Also if perchance you are not interested in maintaining this or other Lua projects at this time we could probably consider helping find new maintainer(s) by migrating it to @lunarmodules.

**Comment by hoelzro** [comment]
@alerque Thanks for letting me know about the downstream packaging issue, and also about @lunarmodules as an option!  I'll try to cut a release in the next few days.

**Comment by hoelzro** [comment]
@alerque I just created a tag for 0.08 and uploaded the rockspec to luarocks.org - please let me know if that looks right and if there's anything else you need from me!

**Comment by alerque** [comment]
Looks good to me. And the Arch Linux package is updated to match so I can disregard the requests to patch.

Thansk for that, always better to have things fixed upstream in my opinion.

**Comment by hoelzro** [comment]
I completely agree 🙂 Thanks for your work packaging this up for Arch!
