### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by Rx1513** [hoelzro/lua-term#28]
Hello, I'm user of your library and I would like to know what the purpose of additional zero in version number.

**Comment by hoelzro** [comment]
Hi! I just never release things as "1.x" when I start them to communicate to users , and I suppose I forgot to change this library over to 1.x!

**Comment by Rx1513** [comment]
Maybe I put it wrong, but I meant the tag version and the rockspec version. I do not understand why it is different, because such a difference makes the package building inconvenient. Can you please use same versions for both spec and tags? I mean instead of Rel.x for spec and Rel.0x use same format?

**Comment by hoelzro** [comment]
Ah, I see what you mean!  I honestly have no idea why I did things that way - would it help if I just created new tags such as `0.8`?

**Comment by Rx1513** [comment]
Yes, of course!

**Comment by hoelzro** [comment]
@Rx1513 Done!

**Comment by Rx1513** [comment]
Thank you!
